<!DOCTYPE html>
<html lang="">
<head>
    <title>RD</title>
</head>
<body>
<h1>Hello, it's my message</h1><hr>
<h4>messages</h4>

<#list messages as message>
<div>
    ${message.text}<br>
    ${message.timeCreate} <input type="submit" value="delete"><br>
</div>
</#list>

<form action="home/message/create" method="post">
    <input type="hidden" th:name="${_csrf.parameterName}" th:value="${_csrf.token}" />
    <label>
        <input type="text" name="text"/>
    </label>
    <input type="submit" value="send"/>
</form><br>
<form action="@{/logout}" method="post">
    <input type="submit" value="Sign Out"/>
</form>
</body>
</html>
